### PR TITLE
fix: correct the `exports` path

### PR DESCRIPTION
**Pull request by eventualbuddha**

### CODE REVIEW

**Comment by thecrypticace** [comment]
I figure you're probably working on this but I'll leave a note anyway just in case :)

Since the export change & wrong path were included in 1.1.7 & 1.2.0 you'll likely need to unpublish those versions for any packages relying on 1.x

**Comment by eventualbuddha** [comment]
Yep, fixing. Sorry about that.

**Comment by eventualbuddha** [comment]
Unfortunately I could no longer unpublish 1.1.7 and 1.2.0. I published 1.1.9 and 1.2.1 to address the issue. Hopefully that's sufficient.

**Comment by thecrypticace** [comment]
🎉 Thanks! I confirmed that the 1.1.9 and 1.2.1 both fix the issue!

**Pull request merged**
