### PR TITLE
fix: add `types` field to `exports` in `package.json`

### PR DESCRIPTION
**Pull request by eventualbuddha**
Replacement for https://github.com/eventualbuddha/lines-and-columns/pull/217, since I needed to change the commit message but couldn't on @sosukesuzuki's fork.

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
Thank you

**Review by sosukesuzuki — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
This can be merged?

**Comment by danielegarciav** [comment]
Indeed this should be able to fix the problem at #217 which is explained in [are-the-types-wrong's article for untyped resultion](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/UntypedResolution.md). I can confirm patching the module with the change fixes the problem.

Is there anything else needed to merge this?

**Review by asd585140-glitch — COMMENTED** [review]
خط عريض للصفحات والنظام

**Pull request merged**
